apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi